services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "ilias1test/postgres-challenge"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - challengedb:/data/challenge_postgres
    ports:
      - "5432:5432"
    networks:
      - challenge-network
    restart: unless-stopped
  challenge-app:
    depends_on:
        - postgres
    build:
      context: .
      dockerfile: app.dockerfile
      target: base
    image: "ilias1test/app-challenge"
    restart: unless-stopped
    volumes:
      - ./src:/home/node/app/src
    environment:
      - DB_HOST=postgres
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DB
      - DB_PORT=5432
    env_file:
      - .env 
    container_name: challenge-app
    expose:
      - '3000'
    ports:
      - '3000:3000'
    networks:
      - challenge-network
    command: npm run start
volumes:
    challengedb:
      external: true
networks:
  challenge-network:
    external: true